# Generated by Django 4.2.7 on 2025-06-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devEUI", models.CharField(db_index=True, max_length=16, unique=True)),
                (
                    "latest_status",
                    models.CharField(
                        blank=True,
                        choices=[("passing", "Passing"), ("failing", "Failing")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fCnt", models.IntegerField()),
                ("raw_data", models.CharField(max_length=255)),
                ("decoded_data", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("passing", "Passing"), ("failing", "Failing")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payloads",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("device", "fCnt")},
            },
        ),
    ]
